print(len("123"))
print(type(123))
print(type("hell"))
print(type(123))
print(type(123.2))
print(type(True))
name_of_user = input("Enter your name")
length = str(len(name_of_user))
print(type(length))
print("Number of letters in your name: " + length )